### ISSUE TITLE
Sensitivity slider in Settings window

### ISSUE THREAD

**Issue by juangpc** [mne-tools/mne-qt-browser#103]
This is mentioned in #85. 

It seems like the functionality of this sensitivity slider is very similar to what the user might achieve by widening the time window shown in the browser. 

Is this the correct behavior?

Please, feel free to close this issue if in fact the sensitivity slider has the correct behavior.

**Comment by marsipu** [comment]
@juangpc Thank you for your great work on the settings and toolbar-tests.
The sensitivity slider changes the amount scrolled (via mousewheel or keyboard) relative to the shown duration. So it is similar but not the same.

We once had a discussion if this is YAGNI. I thought it might be nice for example if you use a horizontal scroll wheel. But usually this is also adjustable in the settings of your mouse-driver. WDYT?

**Comment by juangpc** [comment]
You're welcome. 

I see. I don't see any problem having it. I'll close this.
