### ISSUE TITLE
Plot not show

### ISSUE THREAD

**Issue by ts-mindyourmind** [mne-tools/mne-qt-browser#115]
Hi, I am running mne(v = 1.0) on VScode(Jupyter notebook) on macOS with M1 chip. I wanted to plot the raw data in the new qt-browser. But it only popped up the window, but no time series showed<img width="1151" alt="image" src="https://user-images.githubusercontent.com/72733582/162984369-98831256-3990-43f1-8d7b-b5c4d5720b9d.png">
And the error message showed `ImportError("Unable to load OpenGL library", *err.args)`

**Comment by hoechenberger** [comment]
Hello @ts-mindyourmind, how did you install `mne-qt-browser`? Could you please paste the output of

```python
import mne
mne.sys_info()
```

I assume you didn't install the `PyOpenGL` package? It's recommended on macOS.

**Comment by agramfort** [comment]
can you try with

raw.plot(scalings="auto")

?

Alex

**Comment by hoechenberger** [comment]
Did you install PyOpenGL?

Also your `mne-qt-browser` is slightly outdated, the latest version is 0.3.0; the latest MNE version is 1.0.1

**Comment by ts-mindyourmind** [comment]
yes, I have installed PyOpenGL. And i upgraded the mne and qt-browser just now. still not working. 
still appreciate your help!

**Comment by ts-mindyourmind** [comment]
okay, i will switch to a new environment and try again.
Thanks again!

**Comment by marsipu** [comment]
@ts-mindyourmind Could your problem be resolved? If so, I will close this issue.

**Comment by ts-mindyourmind** [comment]
Yes, it has been solved. Thank you!

On 12 May 2022, at 15:13, Martin Schulz ***@***.******@***.***>> wrote:



@ts-mindyourmind<https://github.com/ts-mindyourmind> Could your problem be resolved? If so, I will close this issue.
