### ISSUE TITLE
[BUG] additional lines drawn when plotting raw data

### ISSUE THREAD

**Issue by eort** [mne-tools/mne-qt-browser#136]
#### Describe the bug
Plotting with the qt backend causes visual artifacts when plotting raw data. 

![image](https://user-images.githubusercontent.com/8819465/182624644-ae5b8ba7-c9ec-44eb-94e5-aee1c036a285.png)

#### Steps to reproduce
The artifact is present with:
```
mne.viz.set_browser_backend('pyqtgraph')
raw = mne.io.read_raw('qt_plotter_test.fif')
raw.plot(show=True, block=True)
```

and absent when 
```
mne.viz.set_browser_backend('matplotlib')
raw = mne.io.read_raw('qt_plotter_test.fif')
raw.plot(show=True, block=True)
```

![image](https://user-images.githubusercontent.com/8819465/182624777-94327703-46e2-4c44-b8bd-4bb129b73ce1.png)

#### [MWE]: 
The example file can be downloaded from https://we.tl/t-p7x9UcTWG5

#### Additional info: 
https://mne.discourse.group/t/strange-artifact-with-neuromag-meg-data/5331

**Comment by marsipu** [comment]
Unfortunately, I can't reproduce:
![grafik](https://user-images.githubusercontent.com/46245704/182697471-bce7c779-9e36-4a1e-894e-154499df4d5b.png)

My `sys_info`:
```
Platform:         Windows-10-10.0.22000-SP0
Python:           3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 06:57:19) [MSC v.1929 64 bit (AMD64)]
Executable:       C:\Users\marti\anaconda3\envs\mnedev\python.exe
CPU:              Intel64 Family 6 Model 158 Stepping 9, GenuineIntel: 8 cores
Memory:           15.9 GB

mne:              1.1.0
numpy:            1.22.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:            1.8.1
matplotlib:       3.5.2 {backend=QtAgg}

sklearn:          1.1.1
numba:            0.55.2
nibabel:          4.0.1
nilearn:          0.9.1
dipy:             1.5.0
cupy:             Not found
pandas:           1.4.3
pyvista:          0.35.1 {OpenGL 4.4.0 - Build 21.20.16.4526 via Intel(R) HD Graphics 630}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.2
vtk:              9.1.0
qtpy:             2.1.0 {PyQt5=5.15.4}
ipympl:           Not found
pyqtgraph:        0.12.4
pooch:            v1.6.0

mne_bids:         0.11.dev0
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   0.4.dev0
mne_connectivity: 0.4dev0
mne_icalabel:     Not found
```
I also tried it with `mne==1.0.3` where it was the same.

@eort Could you post your `mne sys_info` please?

**Comment by eort** [comment]
Ah, my bad! I was accidentally using a legacy conda environment where I still had version 0.24 active. When I tried it with the version 1.0, I also can't reproduce the artifact. Sorry for the false alarm! I guess the issue can be closed then.
