### ISSUE TITLE
Possibility to remove mne-qt-browser splash screen

### ISSUE THREAD

**Issue by chris7neves** [mne-tools/mne-qt-browser#150]
**Is your feature request related to a problem? Please describe.**
When dynamically adding a MNEQtBrowser to a PyQt layout, the splash screen for mne-qt-browser appears, and replaces the icon for the PyQt5 app with the mne-qt-browser logo.

**Describe the solution you'd like**
I would like to be able to modify a config, or pass an argument to raw.plot() that will disable the splash screen from appearing, and prevent the icon of the PyQt app from being replaced.

**Additional context**
Included is the splash screen as well as the changed icon.

![image](https://user-images.githubusercontent.com/38571540/201011431-fee5d01c-c5bc-4c5a-9cea-6cafcf448b8a.png)

**Comment by cbrnr** [comment]
👍 for adding a parameter such as `show_splash=True`.

**Comment by agramfort** [comment]
no objection

**Comment by fishbacp** [comment]
Was this requested change incorporated into mne-qt-browser 0.4.0"  Is there an argument such as show_splash=False that I can use?
