### ISSUE TITLE
Plot window is blank and freezes (not responding) when launched in PyCharm's Python console or debugger

### ISSUE THREAD

**Issue by jackz314** [mne-tools/mne-qt-browser#151]
#### Describe the bug
The plot window is blank and freezes (not responding) when launched in PyCharm's Python console or debugger. The splash screen shows up normally, but then the plot window itself is blank and the title bar will say "XXX (Not responding)". 

Everything works fine in regular scripts/consoles. pyqt support is enabled in PyCharm, I'm not very familiar with PyQT or QT, but I tried running a hello world example with PyQT5 and it seems to work fine, here's the code:
```python
from PyQt5.QtWidgets import *

app = QApplication([])
button = QPushButton('Click')

def on_button_clicked():
    alert = QMessageBox()
    alert.setText('You clicked the button!')
    alert.exec_()

button.clicked.connect(on_button_clicked)
button.show()
app.exec_()
``` 

#### Steps to reproduce
```python
from mne.io import concatenate_raws, read_raw_edf
from mne.datasets import eegbci
raw_fnames = eegbci.load_data(1, 1)
raws = [read_raw_edf(f, preload=True) for f in raw_fnames]
raw = concatenate_raws(raws)
raw.plot()
```

#### Expected results
Normal interactive plot window.

#### Actual results☺
Blank not responding window.

#### Additional information
Platform:         Windows-10-10.0.19044-SP0
Python:           3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Executable:       C:\Program Files\Python310\python.exe
CPU:              Intel64 Family 6 Model 165 Stepping 5, GenuineIntel: 16 cores
Memory:           31.7 GB
mne:              1.2.0
numpy:            1.23.4 {OpenBLAS 0.3.20 with 16 threads}
scipy:            1.9.2
matplotlib:       3.6.1 {backend=module://backend_interagg}
sklearn:          1.1.2
numba:            0.56.3
nibabel:          Not found
nilearn:          Not found
dipy:             Not found
openmeeg:         Not found
cupy:             Not found
pandas:           1.5.0
pyvista:          Not found
pyvistaqt:        Not found
ipyvtklink:       Not found
vtk:              Not found
qtpy:             2.3.0 {PyQt5=5.15.2}
ipympl:           Not found
pyqtgraph:        0.13.1
pooch:            v1.6.0
mne_bids:         Not found
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   0.4.0
mne_connectivity: Not found
mne_icalabel:     Not found

**Comment by jackz314** [comment]
This seem to be a `pyqtgraph` issue, I've opened a separate issue here: https://github.com/pyqtgraph/pyqtgraph/issues/2530. Not sure if there will be any adjustments required here so I'm leaving the issue open for now.

**Comment by jackz314** [comment]
Partially resolved in https://github.com/pyqtgraph/pyqtgraph/issues/2530, it works in python console now. Still not sure how to make it work in the debugger though.

**Comment by hoechenberger** [comment]
Nice!

**Comment by marsipu** [comment]
@jackz314 Great that you could find some answers yourself. Since PyCharm uses a modified IPython console in their Python Console, I think your issue is also mentioned in our [troubleshooting guide](https://github.com/mne-tools/mne-qt-browser#ipython).

**When you mean debugger, do you mean running you code as a file in PyCharm with the debugger?** Or do you mean running with debugger, setting a breakpoint and then running e.g. `raw.plot()` at the breakpoint?
On my (Windows)-PC the former only shortly shows the plot and then closes, which is expected because the parameter `block=False` by default.
The latter shows the plot without any problems for me.

**Comment by jackz314** [comment]
@marsipu I wanted to achieve the latter one. Turns out for some reason the pycharm debugger wasn't using ipython, and I had pyqt5 and pyside6 installed at the same time, which caused a bunch of other errors, once I purged all the dependency problems debugger plotting worked.

A slight caveat is that the plotting command has to be run in the Console part of the debugger, not in the debugger's Evaluate expression section. Alternatively, you can activate the debug console first, then plotting in the evaluate section will work. This probably needs to be "fixed" in pycharm, but I'm noting this here for people who might have the same problem in the future.

**Comment by marsipu** [comment]
Thank you for sharing you experience with the debugger there, that will certainly be helpful to others
