### ISSUE TITLE
_overview_radio_clicked() takes 1 positional argument but 2 positional arguments were given

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#156]
Originally reported on the forum [here](https://mne.discourse.group/t/mne-qt-browser-positional-argument-error-results-when-trying-to-adjust-overview-modes/6467). I can reproduce on MNE/MNE-QT-Browser main with:

```
from mne import set_config
from mne.datasets import sample
from mne.io import read_raw_fif


set_config("MNE_BROWSE_RAW_SIZE", "20,10")

directory = sample.data_path() / "MEG" / "sample"
raw = read_raw_fif(directory / "sample_audvis_raw.fif", preload=True)
raw.plot(
    show=True, block=True, duration=20, bgcolor="w", color="b", bad_color="r"
)
```

Changing to Z-score fails with:

```
TypeError: MNEQtBrowser._overview_radio_clicked() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given.
```

[Screencast from 03-06-2023 04:10:59 PM.webm](https://user-images.githubusercontent.com/73893616/223150387-e06ced55-fdc2-4a9e-9508-1c9713e1c286.webm)

**Comment by larsoner** [comment]
@mscheltienne can you look into a fix?

**Comment by mscheltienne** [comment]
I had a quick look, but nothing weird strikes me.. and I am not very familiar with Qt, GUI, ...

The method is defined here: https://github.com/mne-tools/mne-qt-browser/blob/e3fec001106fab34db0dc87f121f50dc278ddc40/mne_qt_browser/_pg_figure.py#L3396-L3398

And is linked to the button here: https://github.com/mne-tools/mne-qt-browser/blob/e3fec001106fab34db0dc87f121f50dc278ddc40/mne_qt_browser/_pg_figure.py#L3085-L3087

Not sure what `_methpartial` is for.. https://github.com/mne-tools/mne-qt-browser/blob/e3fec001106fab34db0dc87f121f50dc278ddc40/mne_qt_browser/_pg_figure.py#L2666-L2675

It looks like when the radio button is clicked, `_methpartial: call` is called with `args_=(True,)` and `kwargs_={}`, but I don't know where this extra True is coming from.

**Comment by larsoner** [comment]
I think the hint is in 
```
            radio.clicked.connect(
```
this is a Qt signal:

https://doc.qt.io/qt-6/qabstractbutton.html#clicked

So I think the key is to change some signature to `(self, checked=False, *, ...)` or so
