### ISSUE TITLE
[ENH] Make it possible to toggle visibility of bad channels, especially in butterfly mode

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#170]
I like a lot the butterfly mode, which helps to find big issues in your recording. But it's not that handy on recordings with too many bad channels:

![Screenshot from 2023-06-21 14-57-25](https://github.com/mne-tools/mne-qt-browser/assets/73893616/87bfdfe0-8afb-47f4-8b13-bd51f0af6512)

It would be nice if we could toggle off the visibility of the bad traces.

**Comment by larsoner** [comment]
To me it also looks like there is a big where the bad channel z order is incorrect. It should be lower than the good channels

But yes an option to toggle their visibility would work. An easy way would be too give an option to set the color and if you don't want to see them you just have an alpha of zero for the color you pass

**Comment by mscheltienne** [comment]
True, looks like the good channels are behind. Also a bug.

**Comment by larsoner** [comment]
... looks like `raw.plot(..., bad_color=...)` already exists, so:

1. We should fix the bad channel z order
2. We should make sure an alpha of zero for `bad_color` makes them invisible

**Comment by larsoner** [comment]
@mscheltienne are you on it? If not I can probably look soon

**Comment by mscheltienne** [comment]
Just starting for the bad channel z-order part, I probably have time to fix it before I leave this evening.

**Comment by mscheltienne** [comment]
Fix in #171 works, but maybe there is a better way to do it. I tried also to set the zvalue in `_draw_traces` based on the bads status, but I was not convinced.

For `bad_color`, that's great, but I still think that a toggle would be nice. It doesn't force the user to have the bad channels set before launching the browser, and it allows for someone to select bad channels interactively and then move to butterfly/annotations without having to close/re-open the browser. 
Even with the z-value lowered, on bad datasets, the butterfly mode is too crowded with the bad channels.
