### ISSUE TITLE
OpenGL issue on Ubuntu 18.04.6: Clipped values (NaN) are wrongly interpolated

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-qt-browser#20]
Hi, Thanks for this awesome addition to MNE-Python. I am running into a weird visualization issue that I'd like to report. On the pyqtgraph backend, I see thick black horizontal lines that I don't see on the matplotlib backend. Do you have any idea where they might come from?

# matplotlib

![image](https://user-images.githubusercontent.com/9084751/140770212-27633f0d-b77b-42c0-840d-5fd944598b81.png)

# pyqtgraph

![image](https://user-images.githubusercontent.com/9084751/140770661-3fbef218-9212-42d5-92b6-cb21d5988b8e.png)

# Code used to produce this

Either executing the matplotlib cell or the pyqtgraph cell. I could share the raw data, but I have tried two different files and both have this problem, so I don't think it's the data.

```python
"""Inspect the raw data."""

# %%
import mne

from config import get_sourcedata

# %%
# Load and prepare data
vhdr, tsv = get_sourcedata(2, "single")
raw = mne.io.read_raw_brainvision(vhdr, preload=True)

# Set the EOG and ECG channels to their type
raw.set_channel_types({"ECG": "ecg", "HEOG": "eog", "VEOG": "eog"})

# Set a standard montage for plotting later
montage = mne.channels.make_standard_montage("standard_1020")
raw.set_montage(montage)

# Temporarily remove existing annotations for faster interactive plotting
raw.set_annotations(None)

# %%

with mne.viz.use_browser_backend('pyqtgraph'):
    raw.plot(block=True)


# %%
%matplotlib qt

raw.plot(block=True)
```

# mne-sys-info

click details.

<details>

```
Platform:       Linux-5.4.0-89-generic-x86_64-with-glibc2.17
Python:         3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
Executable:     /home/stefanappelhoff/miniconda3/envs/ecomp_analysis/bin/python
CPU:            x86_64: 8 cores
Memory:         31.2 GB

mne:            0.24.0
numpy:          1.21.2 {blas=openblas, lapack=openblas}
scipy:          1.7.1
matplotlib:     3.4.3 {backend=Qt5Agg}

sklearn:        1.0.1
numba:          Not found
nibabel:        Not found
nilearn:        Not found
dipy:           Not found
cupy:           Not found
pandas:         1.3.4
mayavi:         Not found
pyvista:        Not found
pyvistaqt:      Not found
ipyvtklink:     Not found
vtk:            Not found
PyQt5:          5.15.6
ipympl:         Not found
mne_qt_browser: 0.1.6
```

</details>

**Comment by larsoner** [comment]
@sappelhoff can you check that your PyQtGraph version is at least 0.12.3 (https://github.com/mne-tools/mne-qt-browser/pull/16) ?

**Comment by marsipu** [comment]
@sappelhoff I didn't have similiar issues with the mne-sample-data or other data I tested. 
If the problem still persists with the newest pyqtgraph-version, would it be possible to upload some sample-data from yours?

**Comment by sappelhoff** [comment]
thanks both, will check my version of pyqtgraph tomorrow and let you know.

**Comment by sappelhoff** [comment]
Seems my version of pyqtgraph **is** 0.12.3 :thinking: 

```
pip freeze | grep pyqt
pyqtgraph==0.12.3
```

I'll test with the MNE sample data now

**Comment by sappelhoff** [comment]
I can replicate this with the sample data, but only in the EEG channels:

![image](https://user-images.githubusercontent.com/9084751/141129545-c3fffd17-89f2-4fe9-be4f-cd9456f8642a.png)

![image](https://user-images.githubusercontent.com/9084751/141129788-b972d539-3b00-41a3-b377-40a7ef0a05a3.png)


```python
In [1]: import mne

In [2]: f = "sample_audvis_raw.fif"

In [3]: raw = mne.io.read_raw(f)
Opening raw data file sample_audvis_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 192599 =     42.956 ...   320.670 secs
Ready.

In [4]: raw
Out[4]: <Raw | sample_audvis_raw.fif, 376 x 166800 (277.7 s), ~3.3 MB, data not loaded>

In [5]: with mne.viz.use_browser_backend('pyqtgraph'):
   ...:     raw.plot(block=True)
   ...: 

```

**Comment by marsipu** [comment]
I can't replicate this:
![grafik](https://user-images.githubusercontent.com/46245704/141379298-4c96b732-3771-448d-b687-efdb58b3c990.png)

But I see that there seems to be a problem with samples being NaN where the data is clipped (`clipping=1.5` is the default).
To check this theory, you could set `clipping=None` to see if that makes the thick lines go away.

Normally those NaN samples should be handled by pyqtgraph just as gaps. I see how they are doing this with OpenGL disabled but I have little knowledge about how NaN values are handled with OpenGL enabled. Although it seems to work on most systems, your particular Hardware/Software-Configuration might be an exception.
To test this set `use_opengl=False`.

**Comment by sappelhoff** [comment]
Very interesting, thanks. I'll try both the clipping and opengl thing in all combinations and then report back. BTW, my system:

![image](https://user-images.githubusercontent.com/9084751/141455070-77e844ea-5299-4e4f-bc03-109542c23e3c.png)

**Comment by larsoner** [comment]
I'm guessing it's an OpenGL problem but I thought we made that opt-in. Maybe that will be in 0.24.1, though, and isn't in 0.24.0...

**Comment by sappelhoff** [comment]
`clipping=None` works (because there are no NaNs then):

![image](https://user-images.githubusercontent.com/9084751/141769833-79a7ac4a-9dd4-4358-b073-74380be7d357.png)

but is the "channels overview-mode" supposed to be solid black? I mean the one that turns nicely red-white-blue in "zscore" mode

---

`use_opengl=False` also works (because NaNs are no longer incorrectly interpolated):

![image](https://user-images.githubusercontent.com/9084751/141771028-5c2781f3-6cf2-4ccc-8ab4-d4af29508d5e.png)

but **not** using opengl will probably lead to worse performance (speed), right?

---

So yes, this seems to be an opengl issue related to NaN values when clipping happens on my specific system (Ubuntu 18.04.6). I am happy to close this issue if this is not something to be solved here, let me know ... and thanks for the support and this awesome thing!

**Comment by larsoner** [comment]
OpenGL-off is now the default (or will be in 0.24.1, can't remember?) and on some systems -- including my Linux desktop with a powerful NVIDIA GPU -- it's slower than rendering with the CPU. I'm inclined to close as "yet another reason to leave using OpenGL up to the user" :)

**Comment by drammock** [comment]
> but is the "channels overview-mode" supposed to be solid black?

it is analogous to the right-hand scrollbar in the matplotlib raw browser: a color code for channel type.  Looks like your channels are all EEG.  IMO something like a "minimap" that you see in code editors would be better.

**Comment by larsoner** [comment]
The z-score mode more or less is a minimap I think. So maybe only showing the bottom thing when in z-score mode, and using a vertical one to the just inside or outside of the right scrollbar when in non-zscore mode (more like what we have for matplotlib) would make more sense. That's a lot of horizontal screen real estate dedicated to showing what is really 1D static row-by-row information in the channel-type case.

**Comment by drammock** [comment]
> The z-score mode more or less is a minimap I think.

agreed, it has the function of "see at a glance where you are and where interesting features are, and be able to click-drag the viewbox to move around".  But I think it's a bit less intuitive to interpret than a non-transformed minimap would be; and both are far superior to the current non-zscore option.

> So maybe only showing the bottom thing when in z-score mode

agree, unless a more informative non-zscore minimap can be devised.

> and using a vertical one to the just inside or outside of the right scrollbar when in non-zscore mode

If we're going to add something like this, I don't see why we wouldn't have it visible all the time?  Since it won't need to be clickable (there's a separate scrollbar) it could really be just a few pixels thick.

**Comment by sappelhoff** [comment]
Okay, thanks everyone. Closing this as "leaving open gl to the user" as suggested by Eric. The other discussion seems to have moved to #26.
