### ISSUE TITLE
Q: Release?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-qt-browser#207]
@sappelhoff pointed out that the currently released version of mne-qt-browser uses a deprecated MNE function. Okay for me to cut a quick release? @scott-huberty @drammock I know the channel-specific stuff is not done, but I figure at least having them *display* (even if you can't edit them interactively) is already a good enough step. So even though it would have been nice to release display+interactivity, it might take a while for the interactive stuff to be implemented, and it might be good to have devs use that for a month or two before releasing it anyway.

**Comment by scott-huberty** [comment]
Fine by me!

**Comment by drammock** [comment]
go for it

**Comment by larsoner** [comment]
Cut v0.6.0. Decided to bump up from 0.5.2 since hopefully 0.6 will feature more and more channel-specific stuff :)

**Comment by sappelhoff** [comment]
thanks!
