### ISSUE TITLE
MNT: Add issue-forms with YAML instead of Markdown-templates

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-qt-browser#218]
The issue-forms, as they are already implemented with [mne-python](https://github.com/mne-tools/mne-python/issues/new?assignees=&labels=BUG&projects=&template=bug_report.yml) offer a better user experience and a more streamlined issue output.

[How To Issue-Template GitHub](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
[Syntax Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

**Comment by marsipu** [comment]
@larsoner If okay with the mne-python-developers one could probably copy a lot from[ mne-python](https://github.com/mne-tools/mne-python/tree/main/.github/ISSUE_TEMPLATE).

**Comment by larsoner** [comment]
Yes reusing would be good. mne-bids also has some forms I think

**Comment by masterismail** [comment]
hey ! would like to work on this. Which issue-forms are you guys specifically referring to ? as i can see, some are already implemented in YAML here [mne-python](https://github.com/mne-tools/mne-python/tree/main/.github/ISSUE_TEMPLATE)

**Comment by mscheltienne** [comment]
Feel free to do so, the idea is to add similar issue templates as in [mne-python](https://github.com/mne-tools/mne-python/tree/main/.github/ISSUE_TEMPLATE) and [mne-bids](https://github.com/mne-tools/mne-bids/tree/main/.github/ISSUE_TEMPLATE) in this repository, especially with questions/outputs tailored for `mne-qt-browser`.

**Comment by masterismail** [comment]
have opened a pr #232 , please have a look and let me know if any changes are to be made.
