### ISSUE TITLE
MAINT: Centralize creation of QApp

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-qt-browser#23]
Currently this uses `mkQApp` from `pyqtgraph`, then sets icon, etc. And in #22 more Qt stuff is done regarding QSettings. Ideally we should use a single shared function in MNE-Python for creating a Qt application, deduplicating with 

https://github.com/mne-tools/mne-python/blob/bdedc788b79f7b620167ba6358965ce312ec51be/mne/viz/backends/_pyvista.py#L90-L103

(NB: I think our other Qt application iEEG GUI gets this for free by using https://github.com/mne-tools/mne-python/blob/bdedc788b79f7b620167ba6358965ce312ec51be/mne/gui/_ieeg_locate_gui.py#L154-L155, but that doesn't really apply here)

**Comment by marsipu** [comment]
I agree, something like `_init_qt_app` in `mne.viz.utils`, right?

For QSettings to work, the app-name and app-organization need to be set (the os-dependent stored file will then be named accordingly).

WDYT about:

```
name = 'MNE-Python'
organization = 'MNE'
```

**Comment by larsoner** [comment]
Sounds good to me

**Comment by hoechenberger** [comment]
Would there be a way to properly populate the menu bar on macOS too? By default, it just says "python", which is not very helpful. @cbrnr solved this in MNELAB but I believe it wasn't really trivial?

**Comment by cbrnr** [comment]
It is trivial, you need to install pyobjc-framework-Cocoa and set a value accordingly (https://github.com/cbrnr/mnelab/blob/main/mnelab/__init__.py#L21-L26).

**Comment by marsipu** [comment]
> It is trivial, you need to install pyobjc-framework-Cocoa and set a value accordingly

Thank you @cbrnr. Would it be ok if I copied here how you have done it?

**Comment by cbrnr** [comment]
Of course!
