### ISSUE TITLE
MNE-Qt-Browser hijacks app icon

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-qt-browser#234]
This is a follow-up issue to #233, which fixed icon theme path clashes when MNE-Qt-Browser was started from  MNELAB (and all MNELAB icons disappeared).

A similar problem occurs with the app icon, meaning that if I start MNE-Qt-Browser from MNELAB, the MNELAB app icon is replaced by the MNE-Qt-Browser icon (see https://github.com/mne-tools/mne-qt-browser/blob/main/mne_qt_browser/_fixes.py#L85).

**Comment by larsoner** [comment]
I think this is okay behavior for mne-qt-browser / MNE. You could work around it by detecting when MNE opens a GUI (3D or mne-qt-browser) and setting it back if you want.

**Comment by larsoner** [comment]
Or I suppose we could look into if it's possible to see if the app already has an icon set and if so, don't replace it. @cbrnr want to see if that's possible?

**Comment by cbrnr** [comment]
Unfortunately, it seems like there is no way to set `enable_icon` with the public `raw.plot()` API. Should I add it (it's specific to the qt backend)? Or can you think of a better solution? The problem here is that the browser is spawned from an existing Qt app, and apparently it shares many (all?) of the Qt-specific properties of the parent app.

**Comment by larsoner** [comment]
> Should I add it (it's specific to the qt backend)? Or can you think of a better solution?

It seems overkill to add this param given it's a pretty niche case. We could add a `MNE_SET_QT_APP_ICON` env var or something.

But did you look into this potential solution?

> Or I suppose we could look into if it's possible to see if the app already has an icon set and if so, don't replace it.

Then we need no new param and if someone else has set the app icon (like matplotlib maybe in addition to MNELAB?) we just respect it, which seems okay.

**Comment by cbrnr** [comment]
It is possible to get the current window icon via [`QGuiApplication.windowIcon`](https://doc.qt.io/qt-6/qguiapplication.html#windowIcon-prop), but I don't know if it is possible to distinguish the default from a custom one. I have to check.

**Comment by larsoner** [comment]
Why do you need the window? It should be a property of the QApplication itself, no? We set `qapp.setWindowIcon` in the code. I was expecting something more like this:
```
>>> from qtpy.QtWidgets import QApplication
>>> assert QApplication.instance() is None
>>> app = QApplication([])
>>> app.windowIcon().isNull()
True
```

**Comment by cbrnr** [comment]
I don't need the window, I wrote "window icon" 😄. Yes, something along these lines should be possible. This check would need to go into MNE-Qt-Browser's source, correct? That is, the browser should only set a window icon if it is not already set.

**Comment by larsoner** [comment]
Really it should be fixed in MNE itself
```
$ git grep -n setWindowIcon
mne/viz/backends/_utils.py:188:        app.setWindowIcon(icon)
```
and the `fixes.py` shim removed entirely from mne-qt-browser, it's old enough we don't need it anymore
