### ISSUE TITLE
Add installation instructions?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-qt-browser#33]
Hello, I cannot find user-focused installation instructions anywhere. Is that intentional, given the current rapid development?

**Comment by larsoner** [comment]
I think it's just missing, people should be able to install via `conda-forge` or `pip` as they prefer. Feel free to make a PR to `README.rst` to fix this

**Comment by marsipu** [comment]
Feedback from agramfort:
Add:
- Installation
- Getting started

Explain why `block` is needed!

Logger: Opening Browser, Closing Browser

Toolbar:
- Time/Channels with +/- to for more visual queues
- (Improve icons (maybe different buttons))
- Add tooltips
- Other icon for help (question mark)

Bugs
- SSP Checkboxes not together with toggle-all-button (MacOS)

**Comment by marsipu** [comment]
Fixed with #39
