### ISSUE TITLE
Browser opens behind other windows

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#34]
I don't know if this is only on this machine; and I can't test on others right now; but on this one, the browser opens behind my other windows and I have to minimize each before I can reach the browser. On the contrary, the matplotlib backend does pop up in front, which is way more convenient. 

This laptop is an intel MacBook running macOS Big Sur and python 3.8.10.

**Comment by larsoner** [comment]
+1 for figuring out how Matplotlib avoids this. I know there are ways to force Qt applications to the front, but we should avoid this if possible -- I highly doubt it's what matplotlib does because it breaks things like focus stealing prevention. But I guess if they do it that way, we can/should, too. (I'm hoping they have a solution that is less intrusive.)

**Comment by mscheltienne** [comment]
Briefly, a couple of candidates to look at:

https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/backends/_backend_tk.py#L43-L49

https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/backends/backend_qt.py#L601-L605

https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/backends/backend_wx.py#L1027-L1032

`.activateWindow()`? which is probably what you wanted to avoid..

**Comment by larsoner** [comment]
> .activateWindow()? which is probably what you wanted to avoid..

Agreed it looks like that's what they use. +1 for using the same logic, including looking at the matplotlib rcParams to see if we should actually do it. I assume if a user has this set to False -- which I'm about to do myself! -- we can and should just respect it.

https://matplotlib.org/3.3.0/users/whats_new.html#rcparams-for-controlling-default-raise-window-behavior

We can always add our own MNE_BROWSE_RAISE_WINDOW later if we really want, but I'd assume YAGNI until we see that `rcParams['figure.raise_window']` is not enough.

**Comment by marsipu** [comment]
So do I understand correctly, that we should implement the raising-window-behaviour by default for convenience for users (as @mscheltienne suggests), but deactivate it when the according parameter in rc-params of matplotlib is `False`?
Thank you both for your research!

**Comment by mscheltienne** [comment]
Yes, but it does feel a bit weird however to base our raising window default for a pyqtgraph based library on matplotlib's `rcParams`.

**Comment by larsoner** [comment]
It seems reasonable to me. It's unlikely you'd want it in one case and not the other. And most users of this library are coming as previous matplotlib users.

Someday we could make it use a pyqtgraph-backend configuration variable if found, else use matplotlib. But I'd assume YAGNI until someone pushes for it

**Comment by marsipu** [comment]
@mscheltienne I opened a PR in mne-tools/mne-python#10315
