### ISSUE TITLE
Adding a new annotation displays the textbox very shortly and blocks the browser

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#35]
```
from pathlib import Path

import mne

mne.viz.set_browser_backend('pyqtgraph')


directory = Path(mne.datasets.sample.data_path()) / 'MEG' / 'sample'
fname = directory / 'sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(fname, preload=True)
raw.plot()
```

A video will be clearer than my explanation:

https://user-images.githubusercontent.com/73893616/145994311-89526944-b8df-4e1a-bba6-23dd7f07f707.mov

The browser completely freezes when I try using annotations; I think this is due to a recent change, it was working fine in earlier versions.

Setup:

```
Platform:       macOS-11.6-x86_64-i386-64bit
Python:         3.8.12 (default, Oct 13 2021, 06:42:42)  [Clang 13.0.0 (clang-1300.0.29.3)]
Executable:     /Users/scheltie/Documents/pyvenv/mne/bin/python3
CPU:            i386: 12 cores
Memory:         32.0 GB

mne:            1.0.dev0
numpy:          1.20.3 {blas=openblas, lapack=openblas}
scipy:          1.8.0rc1
matplotlib:     3.5.1 {backend=Qt5Agg}

sklearn:        1.0.1
numba:          0.54.1
nibabel:        3.2.1
nilearn:        0.8.1
dipy:           1.4.1
cupy:           Not found
pandas:         1.3.5
pyvista:        0.32.1 {OpenGL 4.1 ATI-4.6.20 via AMD Radeon Pro 555X OpenGL Engine}
pyvistaqt:      0.5.0
ipyvtklink:     0.2.1
vtk:            9.1.0
PyQt5:          5.13.2
ipympl:         Not found
mne_qt_browser: 0.1.8.dev0
pooch:          v1.5.2
```

**Comment by mscheltienne** [comment]
Could also reproduce on Python 3.9.9:

```
Platform:       macOS-11.6-x86_64-i386-64bit
Python:         3.9.9 (main, Nov 21 2021, 03:23:42)  [Clang 13.0.0 (clang-1300.0.29.3)]
Executable:     /Users/scheltie/Documents/pyvenv/mne/bin/python3
CPU:            i386: 12 cores
Memory:         32.0 GB

mne:            1.0.dev0
numpy:          1.20.3 {blas=openblas, lapack=openblas}
scipy:          1.8.0rc1
matplotlib:     3.5.1 {backend=Qt5Agg}

sklearn:        1.0.1
numba:          0.54.1
nibabel:        3.2.1
nilearn:        0.8.1
dipy:           1.4.1
cupy:           Not found
pandas:         1.3.5
pyvista:        0.32.1 {OpenGL 4.1 ATI-4.6.20 via AMD Radeon Pro 555X OpenGL Engine}
pyvistaqt:      0.5.0
ipyvtklink:     0.2.1
vtk:            9.1.0
PyQt5:          5.13.2
ipympl:         Not found
mne_qt_browser: 0.1.8.dev0
pooch:          v1.5.2
```

**Comment by marsipu** [comment]
Hello @mscheltienne 
thank you for reporting that bug.

I couldn't reproduce this behaviour on Windows with PyQt-versions 5.12.3 and 5.15.6.
But I would assume that this is a macOs specific issue since modal dialogs are often shown a bit differently than on Linux/Windows.

In your video it seems as if the modal dialog looses focus and is stacked behind the main main window which should by definition be unresponsive when the modal input dialog is shown. But the former shouldn't happen and even being possible.

I notice that your PyQt5 version is 5.13.2. How do you come to use this version (I couldn't install it with pip)?
With the default mne-installation, PyQt5 is currently capped to 5.12.3 because this is the [highest available pyqt-version on conda-forge.](https://anaconda.org/conda-forge/pyqt).
Would using 5.12.3 or even an upgrade to the most recent PyQt5-version with `pip install --upgrade PyQt5` change anything?

To Troubleshoot the modal Text-Dialog, you could use the following code:
```python
import sys
from functools import partial

from PyQt5.QtWidgets import (QApplication, QInputDialog, QPushButton,
                             QVBoxLayout, QWidget)


def show_dialog(parent):
    text = QInputDialog().getText(parent, 'Test Dialog',
                                  'Enter some text')
    print(f'I entered: {text[0]}')


app = QApplication(sys.argv)
main_window = QWidget()
layout = QVBoxLayout()
button = QPushButton('Test modal dialog')
button.clicked.connect(partial(show_dialog, main_window))
layout.addWidget(button)
main_window.setLayout(layout)
main_window.show()
app.exec()
```

**Comment by mscheltienne** [comment]
Damn it, so it is macOS specific.. I'll test the different versions of pyqt5 and the code on Friday.

For the version of PyQt5; I installed it before MNE in the venv with `pip install pyqt5` followed by the MNE and its requirements with `python setup.py develop` and `pip install -r requirements.txt`. It is not outside the boundaries `pyqt5>=5.10,<5.14; platform_system == "Darwin"`.

**Comment by larsoner** [comment]
... And FYI that upper bound is only there because 3D plotting with VTK doesn't work properly with newer versions with HiDPI screens. This library should ideally work with any PyQt>=5.12.

I can also test on my macOS install in the coming days if it would help

**Comment by marsipu** [comment]
I am not sure how (might be tricky with the focus), but we should think about adding tests for those modal dialogs to be accessible on all platforms (and maybe also test for different PyQt-versions if necessary).

**Comment by mscheltienne** [comment]
Let's close this one I guess.. I don't think there is much to do; it's a Spyder bug.

Both code snippet and browser work when run in the venv with `python` or `ipython` command. 
Both fail when run through Spyder..

1 more point in favor of changing my IDE 🤦

**Comment by larsoner** [comment]
Thanks for investigating further @mscheltienne !

**Comment by marsipu** [comment]
Thank you @mscheltienne. Good to know, that Spyder seems to interfere with modal Qt-Dialogs.
@cbrnr, have you had experiences like that too?

**Comment by cbrnr** [comment]
I have never tried to start MNELAB from an interactive interpreter, so I don't know.
