### ISSUE TITLE
Browser Doesn't Open When Running `.plot()`

### ISSUE THREAD

**Issue by ddcas9** [mne-tools/mne-qt-browser#37]
Apologies if I'm missing something very obvious, but when executing `raw.plot()`, the browser doesn't open a window, even behind other windows. I'm running the script in the tutorial here on an Intel mac with Big Sur: 

https://mne.tools/mne-bids/stable/auto_examples/read_bids_datasets.html#sphx-glr-auto-examples-read-bids-datasets-py

**Comment by marsipu** [comment]
Hi @ddcas9,

which operating system are you using?
Try adding the following parameter `block=True` to your tutorial script like `raw.plot(block=True)`. Does it help?

And thank you for opening this issue, it is not obvious that `raw.plot()` does not work right out of the box and we need to work on that.

**Comment by ddcas9** [comment]
Hi @marsipu, 

Right, that works! I should have reviewed the docs a bit more to see that you can do that, it's pretty apparent there! I'll close this.

**Comment by marsipu** [comment]
@ddcas9 Your issue is totally valid, thanks for pointing it out

**Comment by marsipu** [comment]
@ddcas9 Another solution without having to change the tutorial-script would be using the interactive-flag for the python-interpreter:
```
python -i read_bids_dataset.py
```
