### ISSUE TITLE
Something is wrong with the vertical offsets when marking channels as bad, sometimes (??)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-qt-browser#44]
Sorry, worst bug report ever, because I don't really know what's going on and I cannot reliably reproduce. But I just encountered this problem and immediately recorded a screencast to capture the issue:

https://user-images.githubusercontent.com/2046265/153367937-dcc00f19-c723-484d-b918-81c6c542dc9a.mov

Could it have something to do with the visibility of the Annotations widget box?

**Comment by marsipu** [comment]
@hoechenberger Thank you for finding this bug. In fact I already fixed it weeks ago in my epochs_support-branch and I do see now how it would have been better to have opened a separate PR for that. Now I learned about "cherry-picking":smiley::cherries:
