### ISSUE TITLE
Name of the backend in MNE-Python

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-qt-browser#45]
To make use of this amazing package, I have to refer to it as `pyqtgraph` backend in MNE-Python. This is super technical and its name has nothing to do with the name of this package (well, of course, except for the `qt` bit)
Any chance we could simply name the backend `qt` or so? At least in the public API?

cc @larsoner

**Comment by marsipu** [comment]
Yes, I would also like "qt" much better :thumbsup:
