### ISSUE TITLE
Plotting epochs on MacOS with multiple colors causes Segmentation Fault when use_opengl=False

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-qt-browser#53]
#### Describe the bug
On **MacOS** when plotting **epochs** with multiple colors (bad epochs, bad segments from autoreject) without OpenGL (`use_opengl=False`), on opening the plot or after scrolling a bit a **segmentation error** is raised and python quits.

![Bildschirmfoto 2022-02-13 um 12 37 52](https://user-images.githubusercontent.com/46245704/153751263-1cbd4994-8978-45c7-b152-3086af760228.png)

#### Code to reproduce
<details>
<summary>Code</summary>

```python
import mne
import os
import numpy as np

import faulthandler
faulthandler.enable()

from mne.viz import use_browser_backend

# Load Raw
sample_data_folder = mne.datasets.sample.data_path()
raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                        'sample_audvis_raw.fif')
raw = mne.io.read_raw(raw_file)

# Load Events
events_path = os.path.join(sample_data_folder, 'MEG', 'sample',
                           'sample_audvis_raw-eve.fif')
events = mne.read_events(events_path)

# Add test-annotations
onsets = np.arange(2, 8, 2) + raw.first_time
durations = np.repeat(1, len(onsets))
descriptions = ['Test1', 'Test2', 'Test3']
for onset, duration, description in zip(onsets, durations, descriptions):
    raw.annotations.append(onset, duration, description)

epo = mne.Epochs(raw, events)

epoch_col1 = np.asarray(['b'] * len(epo.ch_names))
epoch_col1[::2] = 'r'
epoch_col2 = np.asarray(['r'] * len(epo.ch_names))
epoch_col2[::2] = 'b'
epoch_col3 = np.asarray(['g'] * len(epo.ch_names))
epoch_col3[::2] = 'b'
epoch_colors = np.asarray([['b'] * len(epo.ch_names) for _ in
                           range(len(epo.events))])
epoch_colors[::3] = epoch_col1
epoch_colors[1::3] = epoch_col2
epoch_colors[2::3] = epoch_col3
epoch_colors = epoch_colors.tolist()

epo.info['bads'].append('MEG 0113')

with use_browser_backend('pyqtgraph'):
    epo.plot(block=True, n_epochs=10, events=events, epoch_colors=epoch_colors,
             precompute=False, picks=epo.ch_names, use_opengl=True)
```
</details>

#### Possible factors leading to segmentation fault

- **multiple colors**:
For multiple colors additional instances of `DataTrace` are created. They are equally added to the main plot, just the methods differ depending on wether the trace is a child- or a parent-trace.

- **MacOS**
Why does this bug only appear on MacOS, but not on Ubuntu and Windows?

- **Data**
The multiple colored traces of one channel access the same data-array, **BUT** the array is copied with `np.copy` and it is accessed the same way for `openGL=True` which works.

#### Additional information
<details>
<summary>Sys Info</summary>

Platform:       macOS-10.15.4-x86_64-i386-64bit
Python:         3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:28:27)  [Clang 11.1.0 ]
Executable:     /Users/martinschulz/opt/anaconda3/envs/mnedev/bin/python3.9
CPU:            i386: 8 cores
Memory:         16.0 GB

mne:            1.0.dev0
numpy:          1.22.2 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:          1.8.0
matplotlib:     3.5.1 {backend=MacOSX}

sklearn:        1.0.2
numba:          0.53.1
nibabel:        3.2.2
nilearn:        0.9.0
dipy:           1.4.1
cupy:           Not found
pandas:         1.4.1
pyvista:        0.33.2 {OpenGL 4.1 INTEL-14.5.22 via Intel(R) Iris(TM) Plus Graphics 655}
pyvistaqt:      0.7.0
ipyvtklink:     0.2.2
vtk:            9.0.3
PyQt5:          5.12.3
ipympl:         Not found
pooch:          v1.6.0

mne_bids:       0.10.dev0
mne_nirs:       Not found
mne_features:   Not found
mne_qt_browser: 0.2.0
mne_connectivity:0.3dev0
</details>

**Comment by marsipu** [comment]
@larsoner I am pretty stuck with this one. The traceback doesn't give much information and I can't find the reason why MacOS is solely affected.
Can you reproduce?

**Comment by larsoner** [comment]
I just scrolled around for probably 3 minutes using arrow keys and mouse clicks and never got a segfault. I did see this warning:
```
/Users/larsoner/python/mne-qt-browser/mne_qt_browser/_pg_figure.py:2732: RuntimeWarning: PyOpenGL was not found and OpenGL can't be used!
Consider installing pyopengl with "pip install pyopengl"or set "use_opengl" to False to avoid this warning.
  warn('PyOpenGL was not found and OpenGL can\'t be used!\n'
```
So I assume it wasn't actually using OpenGL for me

**Comment by marsipu** [comment]
Did you click on traces for bad-epochs and use the code snippet for multi-colored epochs? This seems to be the cause somehow

**Comment by larsoner** [comment]
I re-ran your code snippet, clicked around a lot, marking various epochs bad and good, scrolling around, etc., and couldn't trigger any segfault

**Comment by marsipu** [comment]
Ok, so great news in principle, I am a bit relieved. On my machine (sys info) which is in fact a hackintosh I just got from a friend to debug MacOS-issues may have some hardware limits as well as maybe the CIs which seem affected too.
I will turn the tone of the warning for Epochs down then a little. @larsoner Do you think I should leave this issue open then?

**Comment by larsoner** [comment]
If there is a workaround in place, we can close and reopen later if needed
