### ISSUE TITLE
Issue with PyOpenGL on macOS since Big Sur

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-qt-browser#69]
@agramfort ran into this issue:
https://github.com/mcfletch/pyopengl/issues/55
https://github.com/mcfletch/pyopengl/issues/72

It appears to me `PyOpenGL` maintenance could be in a better shape … I suppose we could monkey-patch it for now?

**Comment by cbrnr** [comment]
If the project is inactive and there are fixes I think this would be a viable solution. However, I'd still make sure to make upstream PRs with our changes (hoping that the maintainers will merge them at some point).

**Comment by hoechenberger** [comment]
I agree @cbrnr 

Just thought that maybe pushing out a hotfix plus nee installers could make sense

**Comment by hoechenberger** [comment]
The problem does not occur with Python 3.9 and newer. So the easiest "fix" is to just update Python!
