### ISSUE TITLE
The event loop

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-qt-browser#72]
When plotting from an interactive Python session (IPython, Jupyter), the plot window opens and freezes unless one passes `block=True`, which **is** mentioned in the docs here but not intuitive for our users. It has to do with the Qt event loop.

In fact, I felt the urge to point out this behavior in a service tweet:
https://twitter.com/mne_news/status/1506938707705802753

There must be a way to make this behavior better and work without freezing the window even if `block` is not passed. @GuillaumeFavelier achieved something like this with `Brain`, maybe you could share your wisdom here? 🙏

**Comment by GuillaumeFavelier** [comment]
I looked at the code and it seems to me that the browser is really designed to have `block=True`. It's just so much simpler to let Qt handle the events. Otherwise we have to handle them manually.

After some tinkering of both `mne-python` and `mne-qt-browser`, I managed to obtain something similar to `Brain`. But that alone is not enough because now `resizeEvent`, `closeEvent`, `drawEvent`, ...etc all require explicit calls to `app.processEvents()` to work properly. Meaning we would need at least a `QThread` or something to call it regularly for us.

**Comment by GuillaumeFavelier** [comment]
>  Otherwise we have to handle them manually.

But it's not impossible, I'll share what I have ASAP :+1:

**Comment by hoechenberger** [comment]
Is it possible to detect whether we're running inside IPython / Jupyter? (Last time I looked there was no easy way to do so, but it's been a while!)
Because then, we could change the default to `block=None`, and if we're running in IPython / Jupyter, we'd treat this as `block=True`.

**Comment by hoechenberger** [comment]
… or we automatically run the IPython magic, `%matplotlib qt` … As described in the troubleshooting section of the readme:
https://github.com/mne-tools/mne-qt-browser#ipython

**Comment by hoechenberger** [comment]
First users are reporting this problem. We should find a solution soon.

https://mne.discourse.group/t/pybrain-m-eeg-analysis-with-mne-python-problem-to-visualize-the-raw-data/

**Comment by hoechenberger** [comment]
Another user reported this issue:

https://mne.discourse.group/t/silent-error-hanging-raw-plot/

**Comment by cbrnr** [comment]
Would reverting the default to the matplotlib backend be an option? I still think that it was too early to switch. The new browser is awesome, but it is probably not quite ready to be the default.

**Comment by hoechenberger** [comment]
> Would reverting the default to the matplotlib backend be an option? I still think that it was too early to switch. The new browser is awesome, but it is probably not quite ready to be the default.

I'd rather do a two-day hackathon with @GuillaumeFavelier and @marsipu to resolve this now at once and for all, since we'll have to push out an update anyway

**Comment by hoechenberger** [comment]
> Because if I understand correctly, the unexpected behaviour of the app freezing only happens when `block=False` (default) right?

If block=True OR if the user didn't run %matplotlib qt

**Comment by GuillaumeFavelier** [comment]
Forcing `%matplotlib qt` might have an impact on `matplolib` plots not related to `mne-python` no?

**Comment by hoechenberger** [comment]
> Forcing `%matplotlib qt` might have an impact on `matplotlib` plots not related to `mne-python` no?

Yes
