### ISSUE TITLE
closing settings dialog gives error

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-qt-browser#78]
#### Describe the bug
Closing the settings dialog gives an error.

#### Steps to reproduce
```py
import os
import numpy as np
import mne

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_filt-0-40_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)
raw.plot()
```

Now open and close the settings dialog

#### Expected results
No error

#### Actual results☺
I get:

```py
Traceback (most recent call last):
  File "/Users/mainak/anaconda3/envs/mne/lib/python3.9/site-packages/mne_qt_browser/_pg_figure.py", line 4074, in _toggle_settings_fig
    self.mne.fig_help.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

#### Additional information
I'm on the latest branch of MNE and last stable install of mne-qt-browser

**Comment by mscheltienne** [comment]
I got a similar one when closing the settings dialog, running latest dev version of `mne` and `mne_qt_browser`. The error is a bit different: 

`TypeError: closeEvent() takes 1 positional argument but 2 were given`
