### ISSUE TITLE
show time points in datetime format

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-qt-browser#79]
when looking at EEG data in a clinical context it's important for me to know in absolute time when the data was collected. The viewer shows time in seconds and I would love to see the time in datetime format. For this you need to look at the `info['meas_date']`

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/161052/160838128-92cd6a49-0138-4f8c-9d2a-21ab064f549e.png">

@marsipu do you have time to look?

**Comment by marsipu** [comment]
Yes, it should be implemented with pressing `t` or passing `time_format='clock`.

_@agramfort Unfortunately I am not available until next week because this is where I have my big exam_

**Comment by marsipu** [comment]
Thank you 😊

**Comment by agramfort** [comment]
I learnt something ;)

it works as expected

🙏

**Comment by hoechenberger** [comment]
To me it indicates we should start thinking about adding a proper menu. Using keyboard shortcuts is great and all, but we have so much cool functionality that simply goes unnoticed by users -- and even developers!!!

**Comment by cbrnr** [comment]
Yes, and I would do that for the Matplotlib browser as well!
