### ISSUE TITLE
[ENH] preload with option for numpy memory-mapping

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-qt-browser#8]
Coming from a suggestion of @larsoner:
> Give users some way to use NumPy memmapping to map the preloaded data array to a file on disk. (This basically gives you an object that is a standard ndarray but instead of living in memory, it lives on disk.) We have this available for raw data already with read_raw_fif(..., preload='some_str_path') for example, so I don't think it would be too difficult to implement.

**Comment by marsipu** [comment]
@larsoner Do you think this is still a feature needed now with `auto`-mode for `precompute` established?

**Comment by larsoner** [comment]
YAGNI until we see otherwise
