### ISSUE TITLE
Improve dark mode

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#83]
Earlier today, on an env with the latest dev version of `mne` and `mne_qt_browser` on my MacBook, the `raw.plot()` I opened were in dark mode/theme. And sure I do like dark mode usually, but here it was really not that great and made the examination of the signal a pain. 

**Feature request**: 
- [ ] in the setting window, a toggle for light/dark theme.
OR
- [ ] in the setting window, a drop-down list to select the theme.

**Bug**:
- [ ] on macOS, with dark mode enabled at the system level, the argument `thene='light'` in `raw.plot()` is ignored.

----------

I think the MacBook is set up in dark mode at the system-level, which is not the case on the Windows PC I'm using at the moment where the `raw.plot()` do not display with a dark theme.

**Comment by hoechenberger** [comment]
> but here it was really not that great and made the examination of the signal a pain.

Could you explicate what was the issue specifically?

**Comment by mscheltienne** [comment]
I'll make a couple of screenshots tomorrow, traces had a ~white-ish color while the background was a very dark black.. 
It's not really an issue, as I am sure some people love it this way; but for me, it wasn't a theme I enjoyed using.

**Comment by larsoner** [comment]
In the meantime there is a `theme` arg to raw.plot, along with a `MNE_BROWSER_THEME` config var

https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.plot
https://github.com/mne-tools/mne-python/pull/10418

But I agree we should keep this open to allow toggling it in the browser itself, maybe via a toolbar button or something

**Comment by hoechenberger** [comment]
> I'll make a couple of screenshots tomorrow, traces had a ~white-ish color while the background was a very dark black.. 
> 
> It's not really an issue, as I am sure some people love it this way; but for me, it wasn't a theme I enjoyed using.

I was mostly asking because it could be that we need to adjust the theme to make accessibility better. Could be that we need to adjust colors or line width or so to reach a reasonable contrast.

**Comment by mscheltienne** [comment]
Oh, I completely missed this `theme` argument! Thanks!
However, it does not work 😅 and the theme remains dark as on the screenshot below.

So starting with a 64 EEG recordings, with large annotations:

![Screenshot 2022-03-31 at 11 11 48](https://user-images.githubusercontent.com/73893616/161020454-4d28fed1-6749-473b-ae88-bba455a48a32.png)

Then with a sample dataset from MNe including MEG / EEG with no annotations:

![Screenshot 2022-03-31 at 11 14 01](https://user-images.githubusercontent.com/73893616/161020952-074bbc1d-db2b-4157-8999-6f152a7dada8.png)

And finally an ECG single channel with tons of annotations:

![Screenshot 2022-03-31 at 11 17 33](https://user-images.githubusercontent.com/73893616/161021598-b186f8ae-ed05-4751-b8c6-8fd7635b2732.png)

![Screenshot 2022-03-31 at 11 17 54](https://user-images.githubusercontent.com/73893616/161021655-65b42043-6660-49c6-b9bc-79080673f602.png)

-----------

For me, the dark of the viewing area is too dark, and I would have preferred a color closer to the background of the toolbar. Also, I prefer the browsing experience in light mode as soon as I have annotations. This is only my personal taste, and I'm a bit color-blind, so don't give too much attention to my color taste 😉 

-----------

Anyway, a toggle or theme drop-down list in the settings of the browser would be nice, and the `theme` argument did not work for me on this computer (macOS, and I think I have the dark mode enabled at a system level).

**Comment by larsoner** [comment]
> A common way to approach dark mode is to have only certain UI elements like buttons and toolbars and window borders in a dark color, and the rest -- especially text fields and such -- in light colors for better readability.

For some software at least this is probably true, but not in all. I drew my inspiration from MS Word and Chrome in https://github.com/mne-tools/mne-qt-browser/pull/67. In MS word, it inverts by default the doc background (to black) and text (to white) in dark mode, and Chrome at least has an option to use CIELab-based inversion, which is what I ended up implementing.

FWIW, though, CIELab was (reasonably) rejected by the pydata-sphinx-theme folks because it's not as good as custom-chosen colors.

> I think we ought to find a background color for the traces that works with both dark and light themes, and always remains the same?

I guess that would be white, i.e., don't invert the plotted elements :(

The best approach to me would be the one used by the pydata-sphinx-theme folks, namely to actually hand-pick colors in both modes. We've already done this for "light" mode implicitly, so we "just" need to do it for the dark mode elements. The CIELab-inverted colors could at least be some sort of starting point...

**Comment by agramfort** [comment]
personally I find the dark mode not usable. The contrast is poor for MEG
line plots for example

**Comment by hoechenberger** [comment]
> personally I find the dark mode not usable. The contrast is poor for MEG
> line plots for example
> 

I second this. 

But I even have issues with the super thin lines in light mode. They're very difficult to see for me. I don't have the best eyesight, but high-quality displays.

**Comment by cbrnr** [comment]
I think we should choose reasonable defaults for both light and dark modes, but also let users customize all colors if they want. This could then also be a setting in the config.

**Comment by marsipu** [comment]
I think we can close this since this was improved in #108

**Comment by marsipu** [comment]
> Feature request:
> 
> in the setting window, a toggle for light/dark theme.
> OR
> in the setting window, a drop-down list to select the theme.

I forgot this

**Comment by mscheltienne** [comment]
@marsipu Did you want this issue to stay open?

**Comment by marsipu** [comment]
The option in the settings for the theme is still not implemented, but maybe we can open a separate issue for this?

**Comment by mscheltienne** [comment]
Sounds good in a separate issue.
