### ISSUE TITLE
ENH: Move "overview mode" selector to toolbar

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-qt-browser#86]
I understand the motivation for putting the "overview mode" selector at the bottom, because it places it closer to the overview bar. However, it creates a big waste of screen real estate, e.g. [here](https://mne.tools/dev/auto_tutorials/intro/15_inplace.html#sphx-glr-auto-tutorials-intro-15-inplace-py):

![](https://mne.tools/dev/_images/sphx_glr_15_inplace_002.png)

I propose to move it up into the toolbar. It's used rarely enough that I think the user experience degradation from having to move the mouse farther is acceptable given the screen space gains for showing traces.

cross-ref https://github.com/mne-tools/mne-python/issues/10481

Also, since the x-axis label is *always* either "time (sec)" or "epoch", perhaps it makes sense to move the label to the left of the numbers (aligned with the channel labels) or even just remove it altogether. I don't think people will be confused about what is being shown, and it gains us more vertical screen real estate.

Thoughts on these two ideas @marsipu @agramfort @hoechenberger ?

**Comment by agramfort** [comment]
+1 to simply remove the overview mode

**Comment by larsoner** [comment]
> +1 to simply remove the overview mode

I assume you mean the "overview mode selector" and not "overview mode itself"... but then users can't switch between modes, which seems useful. I'd rather at least move it to the toolbar so that it still exists!

**Comment by agramfort** [comment]
yes the selector. to be honest I don't understand what it offers :)

**Comment by larsoner** [comment]
```
$ mne browse_raw ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif
```

| channels (default) | empty | zscore |
| -- | -- | -- |
| ![Screenshot from 2022-04-01 10-02-26](https://user-images.githubusercontent.com/2365790/161279149-c793400b-e0a4-48cd-a566-6ec9ee12359d.png) | ![Screenshot from 2022-04-01 10-02-57](https://user-images.githubusercontent.com/2365790/161279225-04958b85-9710-4715-a2fe-94cacebb7e25.png) | ![Screenshot from 2022-04-01 10-03-01](https://user-images.githubusercontent.com/2365790/161279238-5b3d27fb-f2b5-45cd-99ca-51140421b34b.png)

**Comment by cbrnr** [comment]
The overview bar should be hidden/off by default because it takes up so much space (I assume there is an "off" option?). I have to say I like the bar in the Matplotlib backend, which is much narrower but contains annotations, so maybe there could be a "minimal" mode?

And yes, the selector should definitely be moved into the toolbar.

**Comment by agramfort** [comment]
+1 to move the selector up

Regarding the use of empty mode I am not sure to see the use
