### ISSUE TITLE
bus error

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-qt-browser#89]
on my laptop running this code in IPython terminal or jupyter

```
from pathlib import Path
import mne


sample_dir = Path(mne.datasets.sample.data_path())
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(sample_fname, preload=True)
raw.crop(tmax=4)

sfreq = raw.info['sfreq']
first_samp = 0
raw = mne.io.RawArray(raw.get_data(),
                      raw.info,
                      first_samp=first_samp)

raw.plot()
```

gives a bus error:

```
In [1]: %run debug_bus_error_qt_browser.py
[1]    14095 bus error  ipython --matplotlib=qt --no-banner
```

can someone replicate? I don't have any problem without the RawArray creation.

**Comment by hoechenberger** [comment]
Is this on macOS?

**Comment by hoechenberger** [comment]
Are you maybe out of memory? Is you disk full?

**Comment by hoechenberger** [comment]
Lastly, is this a "fresh" conda environment?

**Comment by agramfort** [comment]
no my disk it not full and it's not a fresh conda env. It's my old messy
one :)

but it suggests it's just me then?

**Comment by hoechenberger** [comment]
> but it suggests it's just me then?

Until now apparently yes. The issue is that the bug is very unspecific and I would suspect it has to do with some binary incompatibilities inside your "messy" environment… maybe. 😅

**Comment by agramfort** [comment]
ok fair enough... i'll just close
