### ISSUE TITLE
Couple of bugs: annotation not displayed in the main window, scrolling to the left on the scrollbar outside the window brings you to the right of the scrollbar, and a crash

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-qt-browser#9]
I'm just a normal MNE user, and as I like new features, I read through the PR on the main repo.  I have at the moment some large datasets (1500-2000 -raw.fif files), and I thought that this new browser could really be beneficial to my projects. And damn, it's impressive!! I can't wait to use it more 😄 

A couple of bugs I had on my dataset (64 EEG, 1 EOG, 1 ECG).

```
raw = mne.io.read_raw('path...', preload=True)

with use_browser_backend('pyqtgraph'):
    raw.plot(block=False)
```

1. Making the main window smaller than a full screen (to accentuate the bug) and clicking+holding on the rectangle in the scrollbar, then moving it to the extreme left and then moving the mouse outside the main window cycles the rectangle selection to the right of the scrollbar. 

2. I have some annotations that have been set programmatically on this dataset, and they do render in the scrollbar but not always in the main window.

Depending on the position on the X/Y axis (position of the rectangle on the scrollbar, I get either:

![image](https://user-images.githubusercontent.com/73893616/139500940-21467807-fb8a-4051-ba8b-050287375d41.png)

OR

![image](https://user-images.githubusercontent.com/73893616/139500970-5c4db52f-182d-49be-8951-b931f26ac46e.png)

**UPDATE:** This bug occurs when an annotated segment is not entirely comprised in the viewing window, i.e. when its edges are outside the viewing window. As soon as one of the edges enter the viewing window, the background color comes back on.

3. A crash, no idea what is triggering it exactly. 

```
Traceback (most recent call last):
  File "C:\Users\Mathieu\Documents\pyvenv\mne_pyqtgraph_backend\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 608, in paint
    specs = self.generateDrawSpecs(painter)
  File "C:\Users\Mathieu\Documents\pyvenv\mne_pyqtgraph_backend\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 1057, in generateDrawSpecs
    if tickPositions[i][j] is None:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Mathieu\Documents\pyvenv\mne_pyqtgraph_backend\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 608, in paint
    specs = self.generateDrawSpecs(painter)
```

I haven't counted but it is probably raised a couple of hundred times 😅 

Video:

https://user-images.githubusercontent.com/73893616/139501033-f37d7521-b05c-491f-85f2-3dc0ab2560a5.mp4

**Comment by marsipu** [comment]
@mscheltienne Thanks a lot for your detailed feedback, it is really helpful. I will look into those issues now.

**Comment by marsipu** [comment]
@mscheltienne I think I fixed all the bugs you mentioned now. It was a lot facilitated by your screencast, thank you 👍🏻
